### PR TITLE
Privacy Notice

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Adds a privacy notice page

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@matmair from a documentation side of things, how does this look?

**Review by matmair — APPROVED** [review]
@SchrodingersGat looks good. We need some way to ask for consent before tracking on the docs but then we should be fine.

**Comment by SchrodingersGat** [comment]
I may simply remove GA from the documentation server, this might be the easier option.

https://tutanota.com/blog/posts/google-analytics/

**Comment by matmair** [comment]
@SchrodingersGat that is one of the reasons I was concerned. It takes a while till those things get legally binding, we surely have 3 months till lawyers can get going on that decisions. And there are still legal options.
Max Schrems wins those cases in general. He is a pretty cool dude.

**Comment by eeintech** [comment]
Nice work!

**Pull request merged**
