### PR TITLE
PO/SO doc

### PR DESCRIPTION
**Pull request by eeintech**
WIP: I promise I wanted to write some doc today, but instead I started with making it pretty :stuck_out_tongue_closed_eyes: 

https://inventree--158.org.readthedocs.build/en/158/companies/supplier/

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Any improvements are welcome! Let me know when you think this is ready for review

**Comment by eeintech** [comment]
@SchrodingersGat Ready for review!

Let me know what do you think of the extra CSS to mirror the look of the buttons from the InvenTree UI.
I used a quick and dirty way, would be nice if there was some kind of better way to link the UI to the doc :stuck_out_tongue:

**Comment by SchrodingersGat** [comment]
Fantastic, this looks great! Thanks for the addition :)

**Comment by eeintech** [comment]
Cool, if I find the time and courage, I will try to give the doc some refresh with those new CSS hooks.

**Pull request merged**
