### PR TITLE
Adds docs for fast login

### PR DESCRIPTION
**Pull request by matmair**
Ref: https://github.com/inventree/InvenTree/pull/3465

### CODE REVIEW

**Comment by eeintech** [comment]
@matmair This is an interesting feature but I don't see how the documentation explains how to create fast login URLs...

**Comment by matmair** [comment]
Main idea is that you only need to click the link - I see no value in showing users the login flow. That is just not part of the added value of InvenTree.

**Comment by eeintech** [comment]
Ok I guess I misinterpreted the feature, I thought it would be made available to anybody :smile:

**Comment by matmair** [comment]
@eeintech I see no way to implement something like this in a long-lived, static and safe way. So no - not for production usage.

**Pull request merged**
