### PR TITLE
Backup directory: clarify doc

### LINKED ISSUE #382: Backup dir - Formulation might be unclear
### Body of the issue

In this section: https://inventree.readthedocs.io/en/latest/start/config/#backup-file-storage
> By default, database and media backups are stored in the local directory /home/inventree/backup. This directory should be changed by specifying the backup_dir option in the config file based on the particular installation requirements.
>
> Alternatively this location can be specified with the INVENTREE_BACKUP_DIR environment variable.

I think the formulation is not clear, but I am not completely sure so I want to check before fixing the docs.

Without the `backup_dir` option in the config file, I am encountering this error:
``` bash
File ".../InvenTree/config.py", line 169, in get_backup_dir
raise FileNotFoundError('INVENTREE_BACKUP_DIR not specified')
```

Indeed the code is not checking for any "default" directory:
https://github.com/inventree/InvenTree/blob/9beefd09f75e32066be2e91c64f84e8f055a1b0b/InvenTree/InvenTree/config.py#L163

So the text should say instead:
> Database and media backups **require** a local folder for backup. This directory should be changed...

Or am I mistaken?

### PR DESCRIPTION
**Pull request by eeintech**
Fixes #382

### CODE REVIEW

**Comment by eeintech** [comment]
@matmair I think static and media folders don't have defaults either... please confirm and I can fix.

## Static files directory
Doc: https://inventree.readthedocs.io/en/latest/start/config/#static-file-storage
Code: https://github.com/inventree/InvenTree/blob/9beefd09f75e32066be2e91c64f84e8f055a1b0b/InvenTree/InvenTree/config.py#L147

## Media files directory\
Doc: https://inventree.readthedocs.io/en/latest/start/config/#uploaded-file-storage
Code: https://github.com/inventree/InvenTree/blob/9beefd09f75e32066be2e91c64f84e8f055a1b0b/InvenTree/InvenTree/config.py#L131

**Comment by matmair** [comment]
@eeintech I think this refers to the defaults defined in the template; https://github.com/inventree/InvenTree/blob/9beefd09f75e32066be2e91c64f84e8f055a1b0b/InvenTree/config_template.yaml#L140 we should change the verbiage here too

**Comment by eeintech** [comment]
@matmair Ok I did update those too, let me know if you think it is worth mentioning example paths like in the `config_template.yaml` file

**Comment by SchrodingersGat** [comment]
This language is much better thanks @eeintech

**Pull request merged**
