### PR TITLE
Added What's New page

### LINKED ISSUE #28: Add "whats new" section
As new (major) features are added, some introductory text and a link to the documentation

### PR DESCRIPTION
**Pull request by eeintech**
Targeting to close #28 

Needs to be filled-up with more information for the 0.1.4 release!

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
I like it! This is pretty much exactly what I had in mind. We should add in the "Related Parts" feature too.

**Comment by SchrodingersGat** [comment]
Closed and re-opened to see if the RTD hooks are working...

**Comment by eeintech** [comment]
@SchrodingersGat 0.1.14 seems feature packed! Time for a release? :stuck_out_tongue: 

I believe you are the right person to add more to the new `Build` and `Currency` systems, if you want we can merge this draft.

**Comment by SchrodingersGat** [comment]
Definitely time for a release :) Thanks for adding this page - I'll merge it in and add the extra information about the other features

**Pull request merged**
