### PR TITLE
Added build context variables and an example

### PR DESCRIPTION
**Pull request by SergeoLacruz**

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@SergeoLacruz there are some rendering issues here to address:

image

Are you running a preview of these docs locally on your PC before submitting?

If not you can always view the preview that is generated on each commit:

image

**Comment by SchrodingersGat** [comment]
image

**Comment by SchrodingersGat** [comment]
You'll want to wrap all this in the `{% raw %} ... {% endraw %}` directive I think

**Comment by SergeoLacruz** [comment]
Thanks for the help. Obviously I have no preview system. Will set something up.

**Comment by SchrodingersGat** [comment]
@SergeoLacruz thanks, looks great now

**Pull request merged**
