### PR TITLE
Try config.site_url from macro context to serve images

### PR DESCRIPTION
**Pull request by eeintech**
Reference: https://mkdocs-macros-plugin.readthedocs.io/en/latest/pages/#batteries-included-defaut-variables

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Does this work locally for you?

**Comment by eeintech** [comment]
Yes it does. `config.site_url` returns `http://127.0.0.1/8000` when running with `mkdocs serve` and it returns an empty string when built with `mkdocs build`. I was hoping it returned `https://inventree.readthedocs.io/en/latest/` when served by readthedocs.

**Comment by SchrodingersGat** [comment]
Does not work on the live version, unfortunately.

**Comment by eeintech** [comment]
Just curious, what was the value of `config.site_url`?

**Pull request merged**
