### PR TITLE
New Plugins

### PR DESCRIPTION
**Pull request by matmair**
WIP docs for https://github.com/inventree/InvenTree/pull/2074

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Broken link:

image

**Comment by SchrodingersGat** [comment]
image

Also broken :)

**Comment by SchrodingersGat** [comment]
Thanks, looking better now :)

**Comment by matmair** [comment]
@SchrodingersGat anything I should add here?

**Comment by SchrodingersGat** [comment]
@matmair sorry I didn't see your question, forgot that this was still open. Please fix conflicts and I'll merge in :)

**Comment by matmair** [comment]
@SchrodingersGat ready for merge!

**Pull request merged**
