### PR TITLE
Added documentation to Build and BOM pages

### PR DESCRIPTION
**Pull request by eeintech**
Along with the following improvements:
- Replaced `donate.html` include with a "nicer" looking button
image

- All external URL links get automatic `target="_blank"` tag and a dedicated icon
image

- Removed page title via `extra.css` sheet and edit button (which lead to edit the `inventree/inventree-docs` repo which is read-only for non-owners like me, in other word: useless!) --> More space for actual documentation!

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Amazing! Thanks for this :)

**Comment by eeintech** [comment]
Anytime! After migrating to Mkdocs, I found some motivation inside of me :stuck_out_tongue: 

Readthedocs is pretty slow at building new commits it appears.

**Comment by SchrodingersGat** [comment]
That's because the new commit caused the build to fail!

image

It built on my local machine, but something is going wrong on the server build.

**Comment by SchrodingersGat** [comment]
I think perhaps it is the lines related to the emoji?

**Comment by eeintech** [comment]
Weird... here are the changes for the `mardown_extensions`:
* Added attr_list extension used for the "Donate" button: https://squidfunk.github.io/mkdocs-material/reference/buttons/#attribute-list
* Added metadata extension used for HTML metadata (eg. page title): https://squidfunk.github.io/mkdocs-material/reference/meta-tags/#metadata
* Added emoji extension used to illustrate buttons to click from the InvenTree interface: https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#emoji

**Pull request merged**
