### PR TITLE
Build debug: tentative #2 (disabled emojis)

### PR DESCRIPTION
**Pull request by eeintech**
Try 2...

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
This one seems to work.

image


Can you make another PR which adds the other items back in?

**Comment by SchrodingersGat** [comment]
I'm fine without emoji support if it going to be to irksome to implement.

**Comment by eeintech** [comment]
I may open an issue with the Mkdocs material team to see how to debug this.
It looks like their doc is correct, compared with the pymdownx doc: 

It's more about adding a practical way of linking InvenTree usage of FontAwesome icons with the documentation easily:
image

I basically went to fetch the exact same icons, instead of adding a screenshot...

**Comment by SchrodingersGat** [comment]
Ah ok, I get it - that's a reasonable idea! Alright see if you can work it out :)

**Comment by eeintech** [comment]
@SchrodingersGat Opened an issue with the Material team: https://github.com/squidfunk/mkdocs-material/issues/1943

I'm thinking they gonna say it's a problem with Readthedocs build system, but Readthedocs is a bigger "machine" and they will probably blame the theme instead of understanding the issue. So I'm hoping we get some debug ideas from the Material team :smiley:

**Comment by eeintech** [comment]
Ummm actually I think I found someone who just posted a fix for it: https://github.com/readthedocs/readthedocs.org/pull/7507
From this issue: https://github.com/readthedocs/readthedocs.org/issues/7461#issuecomment-697234615

**Pull request merged**
