### PR TITLE
Add inventree-apprise to third party list

### PR DESCRIPTION
**Pull request by matmair**

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Nice 👍

**Comment by eeintech** [comment]
@matmair [Pipedream](https://pipedream.com/) founder recently contacted me about Ki-nTree, have you heard/played with their software? Not sure it is entirely related to this

**Comment by matmair** [comment]
@eeintech not really sure, seems like some kind of zapier competitor, not really sure what the benefit of that software is.
We can talk about implementation once a user asks, would talk me probably only a few hours to put into a plugin.

**Comment by eeintech** [comment]
Is Zapier OSS? Similar features, API automation.

**Comment by matmair** [comment]
No. Zapier was first and has huge adoption so I prefer it. If real users ask I will make a plugin for pipedream. If I made one for every CEO, founder, and CTO that contacts me there would be 20+ already.

**Pull request merged**
