### PR TITLE
Added temporary debug page to better understand context when hosted on ReadTheDocs

### PR DESCRIPTION
**Pull request by eeintech**
@SchrodingersGat I don't know of any other way to debug #2, if we can have a better idea of the context then maybe we can find out some logic to be able to serve images both locally and on ReadTheDocs without any extra document-er effort.

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Great idea. Let's see what it says.

**Comment by SchrodingersGat** [comment]
https://inventree.readthedocs.io/en/latest/debug/

**Comment by eeintech** [comment]
`mkdocs serve`

docs_dir | str | '/user_local_path/inventree-docs/docs'
-- | -- | --
site_dir | str | '/tmp/mkdocs_xxxxxx'



`mkdocs build`

docs_dir | str | '/user_local_path/inventree-docs/docs'
-- | -- | --
site_dir | str | '/user_local_path/inventree-docs/site'

**Readthedocs**

docs_dir | str | '/home/docs/checkouts/readthedocs.org/user_builds/inventree/checkouts/latest/docs'
-- | -- | --
site_dir | str | '/home/docs/checkouts/readthedocs.org/user_builds/inventree/checkouts/latest/_build/html'

**Comment by eeintech** [comment]
Kinda weird the output of `{{ readthedocs }}`, I guess the context is passed only for Sphinx?

**Comment by eeintech** [comment]
```
{% if 'readthedocs.org' in config.docs_dir %}
{% set assets = '/en/latest/assets' %}
{% else %}
{% set assets = '/assets' %}
{% endif %}
```

Should work? :thinking:

**Comment by SchrodingersGat** [comment]
That seems to have done the trick! Now it works both locally and hosted on readthedocs.

**Comment by eeintech** [comment]
Nice! Well done!

**Pull request merged**
