### PR TITLE
Companies Documentation

### PR DESCRIPTION
**Pull request by eeintech**
* Renamed `Buy` section to `Companies`
* Added pages for manufacturer, customer and sales orders documentation

### CODE REVIEW

**Comment by eeintech** [comment]
@SchrodingersGat I thought it would make more sense to have the full "companies" documentation under the same tab. What do you think?

**Comment by SchrodingersGat** [comment]
I like your suggested layout more than the existing one :)

**Comment by eeintech** [comment]
@SchrodingersGat Ready to merge this part of the doc, I will try to get some doc about purchase/sales orders soon.

**Comment by SchrodingersGat** [comment]
Awesome, I look forward to it! Thanks again for this contribution

**Pull request merged**
