### PR TITLE
Splash screen

### PR DESCRIPTION
**Pull request by SchrodingersGat**

### CODE REVIEW

**Comment by eeintech** [comment]
@SchrodingersGat Looks nice! Unfortunately the screenshot in the carousel are low-res / squished in, maybe some highlighting of small part of the UI could be better? Or ability to zoom in?

**Comment by SchrodingersGat** [comment]
Great point @eeintech - I think some zoomed images would be a great idea here. The images are also having some aspect ratio issues it seems!

**Comment by eeintech** [comment]
I'll see today if I have time to improve the "wow" effect :smile:

**Comment by eeintech** [comment]
@SchrodingersGat Started playing with [lightGallery](https://github.com/sachinchoolur/lightGallery) but then realize there is no easy way to contain it to a `div` element (it is tied up to `body`) and therefore ends-up covering the full page but only when clicking on one of the image thumbnails, like in their demo:
https://www.lightgalleryjs.com/demos/thumbnails/

Could you consider it an option? Maybe instead of the thumbnail tiles, the bootstrap carousel could be playing and on click it would pop up the light gallery.

There are few "pure" JS carousel options, some better than others. Nothing I could find that would load pictures from a pre-defined asset folder, I guess this would have to be done independently.
This library looks interesting: https://splidejs.com/
Have not had to chance to try it out though but I don't see a native "fullscreen-on-click" option...

**Comment by SchrodingersGat** [comment]
splide looks really nice, and is MIT license which is good!

Perhaps we should move to splide and fix https://github.com/inventree/inventree-docs/issues/149

**Pull request merged**
