### PR TITLE
Package installer docs

### PR DESCRIPTION
**Pull request by matmair**
This PR adds the docs for https://github.com/inventree/InvenTree/pull/3743

### CODE REVIEW

**Review by SchrodingersGat — COMMENTED** [review]
Please remove this and add `.vscode/` to .gitignore :)

**Comment by SchrodingersGat** [comment]
Looking good. I think we should also include some information about the database backend which is used by default.

**Comment by SchrodingersGat** [comment]
Also, probably some mention of the two separate processes (webserver / worker)?

**Comment by matmair** [comment]
> Also, probably some mention of the two separate processes (webserver/worker)?

Isn't this enough?
```
## Controlling InvenTree

InvenTree installs multiple services that can be controlled with your local system runner (`service` or `systemctl`).  
The service `inventree` controls everything, `inventree-web` the (internal) webserver and `inventree-worker` the background worker(s).
```

**Comment by SchrodingersGat** [comment]
> > Also, probably some mention of the two separate processes (webserver/worker)?
> 
> Isn't this enough?
> 
> ```
> ## Controlling InvenTree
> 
> InvenTree installs multiple services that can be controlled with your local system runner (`service` or `systemctl`).  
> The service `inventree` controls everything, `inventree-web` the (internal) webserver and `inventree-worker` the background worker(s).
> ```

Sorry, I skipped right over that sentence :) That is sufficient

**Comment by matmair** [comment]
> Looking good. I think we should also include some information about the database backend which is used by default.

The database backend depends on what is set up in the config file; on the install itself it uses SQLite but after that whatever is set in the config file.

Where should I add that?

**Comment by matmair** [comment]
> Please remove this and add `.vscode/` to .gitignore :)

Fun fact: the .vscode folder was already on the gitignore; no idea how it got in there.

**Comment by matmair** [comment]
@SchrodingersGat @eeintech this should be the final stage of these docs. As my English sometimes is a bit technical and german-inspired I would appreciate any feedback.

**Review by SchrodingersGat — APPROVED** [review]

**Comment by SchrodingersGat** [comment]
Thanks for the addition here @matmair :)

**Pull request merged**
